### ISSUE TITLE
code example

### ISSUE THREAD

**Issue by merlinarer** [Skielex/slgbuilder#2]
hello，great job！Is there any code example to use this code for multilabel segmentation？

**Comment by Skielex** [comment]
Yes, there are some links in the readme here: 
https://github.com/Skielex/slgbuilder#examples

The simplest examples are found in this repo: https://github.com/Skielex/slgbuilder-examples
The other links show more advanced use cases.

**Comment by merlinarer** [comment]
Thanks for reply！I am new in graph cut. In my understanding，the smooth term in graph cut problem encourages the segmentation to be smooth as possible，while the data term represents the respose for each label. For example，the shape of input data is hwc，and element ijk indicats the response strength
of pixel in space position ij for label k. 
However，in slgbuilder-examples-DetectLayers.ipynb，the data term is defined as the stack of 4 same input data，how does this work？

**Comment by merlinarer** [comment]
Fully understand，thanks.
