### ISSUE TITLE
multithreading speedup

### ISSUE THREAD

**Issue by merlinarer** [Skielex/slgbuilder#3]
hello，does this python version support the multithreading speedup as fig. 8 in paper
`Review of Serial and Parallel Min-Cut/Max-Flow Algorithms for Computer Vision`？

**Comment by Skielex** [comment]
Yes, you can use the [PQPBO](https://github.com/Skielex/slgbuilder#pqpbo) builder for do parallel optimization. It requires the [shrdr](https://github.com/Skielex/shrdr) package.

Be aware that the optimization problem at hand greatly influences how much can be gained from parallelization.

Notebooks demonstrating how it may be used can be found in the supplementary material here:
https://zenodo.org/record/5201620#.ZB3eNHbMKbg
